ROOT = "nxdev.com"
HOME_URL = "https://" + ROOT + "/"
URL_DASHBOARD = "https://" + ROOT + "/wp-admin/"
URL_NX = "https://" + ROOT + "/wp-admin/admin.php?page=nx-admin"
URL_ADD_USER = "https://" + ROOT + "/wp-admin/user-new.php"
